# Site settings
title: Jackson Lynch
description: > 
  Jackson Lynch is a product designer at Kickstarter.
baseurl: "jacksonthatsme.github.io/jacksonthatsme" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
destination: _build
permalink: /:title